image: debian:10
    
build:
    stage: build
    script:
        - apt-get update
        - apt-get install -y python python-pip python-dev build-essential libssl-dev libffi-dev libpq-dev
        - pip install -r requirements.txt
        - pwd > /usr/local/lib/python2.7/dist-packages/mdedonno.pth
        - make -C ./TPS/TPSCy
        - python ./doctester.py
        - ./coverage.sh
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

