stages:
    - build
    - versions
    - coverage

before_script:
    - docker --version

build:
    stage: build
    script:
        - docker build --pull --no-cache -t tps .

coverage:
    stage: coverage
    script:
        - docker run tps /TPS/coverage.sh
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

python:
    stage: versions
    script:
        - docker run tps python --version

pip:
    stage: versions
    script:
        - docker run tps pip freeze

cython:
    stage: versions
    script:
        - docker run tps cython --version
