stages:
    - build
    - coverage
    - versions

before_script:
    - docker --version

build:
    stage: build
    script:
        - docker build --pull -t tps .

coverage:
    stage: coverage
    script:
        - docker run tps /bin/bash -c "coverage run ./TPSModules_unittest.py && coverage  report --include */TPS/*"
    coverage: '/TOTAL.+ ([0-9]{1,3}%)/'

python:
    stage: versions
    script:
        - docker run tps python --version

pip:
    stage: versions
    script:
        - docker run tps pip freeze

cython:
    stage: versions
    script:
        - docker run tps cython --version
